# Generated by Django 5.0.2 on 2024-03-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, default='I am am Amazing Vendor', null=True),
        ),
    ]
